package neu.edu.entity;
// Generated Apr 26, 2017 2:35:41 PM by Hibernate Tools 5.2.1.Final

/**
 * CategoryId generated by hbm2java
 */
public class CategoryId implements java.io.Serializable {

	private String categoryName;
	private String categoryShow;

	public CategoryId() {
	}

	public CategoryId(String categoryName, String categoryShow) {
		this.categoryName = categoryName;
		this.categoryShow = categoryShow;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryShow() {
		return this.categoryShow;
	}

	public void setCategoryShow(String categoryShow) {
		this.categoryShow = categoryShow;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryId))
			return false;
		CategoryId castOther = (CategoryId) other;

		return ((this.getCategoryName() == castOther.getCategoryName()) || (this.getCategoryName() != null
				&& castOther.getCategoryName() != null && this.getCategoryName().equals(castOther.getCategoryName())))
				&& ((this.getCategoryShow() == castOther.getCategoryShow())
						|| (this.getCategoryShow() != null && castOther.getCategoryShow() != null
								&& this.getCategoryShow().equals(castOther.getCategoryShow())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCategoryName() == null ? 0 : this.getCategoryName().hashCode());
		result = 37 * result + (getCategoryShow() == null ? 0 : this.getCategoryShow().hashCode());
		return result;
	}

}
