package neu.edu.entity;
// Generated Apr 26, 2017 9:36:03 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Creditcard generated by hbm2java
 */
public class Creditcard implements java.io.Serializable {

	private Integer cardId;
	private Users users;
	private String cardNumber;
	private String cardFullName;
	private String cardType;
	private String cardExpireDate;
	private String cardSecurity;
	private Set<Service> services = new HashSet<Service>(0);

	public Creditcard() {
	}

	public Creditcard(Users users, String cardNumber, String cardFullName, String cardType, String cardExpireDate,
			String cardSecurity, Set<Service> services) {
		this.users = users;
		this.cardNumber = cardNumber;
		this.cardFullName = cardFullName;
		this.cardType = cardType;
		this.cardExpireDate = cardExpireDate;
		this.cardSecurity = cardSecurity;
		this.services = services;
	}

	public Integer getCardId() {
		return this.cardId;
	}

	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	public String getCardFullName() {
		return this.cardFullName;
	}

	public void setCardFullName(String cardFullName) {
		this.cardFullName = cardFullName;
	}

	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public String getCardExpireDate() {
		return this.cardExpireDate;
	}

	public void setCardExpireDate(String cardExpireDate) {
		this.cardExpireDate = cardExpireDate;
	}

	public String getCardSecurity() {
		return this.cardSecurity;
	}

	public void setCardSecurity(String cardSecurity) {
		this.cardSecurity = cardSecurity;
	}

	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
