package neu.edu.entity;
// Generated Apr 26, 2017 9:36:03 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer projectId;
	private Users users;
	private String projectName;
	private String projectDesc;
	private String amountGoal;
	private String dayStart;
	private String dayEnd;
	private String category;
	private Set<Service> services = new HashSet<Service>(0);

	public Project() {
	}

	public Project(Users users, String projectName, String projectDesc, String amountGoal, String dayStart,
			String dayEnd, String category, Set<Service> services) {
		this.users = users;
		this.projectName = projectName;
		this.projectDesc = projectDesc;
		this.amountGoal = amountGoal;
		this.dayStart = dayStart;
		this.dayEnd = dayEnd;
		this.category = category;
		this.services = services;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	public String getAmountGoal() {
		return this.amountGoal;
	}

	public void setAmountGoal(String amountGoal) {
		this.amountGoal = amountGoal;
	}

	public String getDayStart() {
		return this.dayStart;
	}

	public void setDayStart(String dayStart) {
		this.dayStart = dayStart;
	}

	public String getDayEnd() {
		return this.dayEnd;
	}

	public void setDayEnd(String dayEnd) {
		this.dayEnd = dayEnd;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
