package neu.edu.entity;
// Generated Apr 26, 2017 9:36:03 PM by Hibernate Tools 5.2.1.Final

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private Integer paymentId;
	private Creditcard creditcard;
	private Project project;
	private String paymentAmount;
	private String paymentDate;
	private String paymentStatus;

	public Service() {
	}

	public Service(Creditcard creditcard, Project project, String paymentAmount, String paymentDate,
			String paymentStatus) {
		this.creditcard = creditcard;
		this.project = project;
		this.paymentAmount = paymentAmount;
		this.paymentDate = paymentDate;
		this.paymentStatus = paymentStatus;
	}

	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	public Creditcard getCreditcard() {
		return this.creditcard;
	}

	public void setCreditcard(Creditcard creditcard) {
		this.creditcard = creditcard;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getPaymentAmount() {
		return this.paymentAmount;
	}

	public void setPaymentAmount(String paymentAmount) {
		this.paymentAmount = paymentAmount;
	}

	public String getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(String paymentDate) {
		this.paymentDate = paymentDate;
	}

	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

}
