package neu.edu.entity;
// Generated Apr 26, 2017 9:36:03 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String firstName;
	private String lastName;
	private String password;
	private String type;
	private String email;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Creditcard> creditcards = new HashSet<Creditcard>(0);

	public Users() {
	}

	public Users(String userName) {
		this.userName = userName;
	}

	public Users(String userName, String firstName, String lastName, String password, String type, String email,
			Set<Project> projects, Set<Creditcard> creditcards) {
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.type = type;
		this.email = email;
		this.projects = projects;
		this.creditcards = creditcards;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	public Set<Creditcard> getCreditcards() {
		return this.creditcards;
	}

	public void setCreditcards(Set<Creditcard> creditcards) {
		this.creditcards = creditcards;
	}

}
